services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Dfile.encoding=UTF-8
      - DB_MODE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=aquariumdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - ./logs:/usr/local/tomcat/logs

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: aquariumdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: 