@baseUrl = http://localhost:8085

GET {{baseUrl}}/api
Accept: application/json

GET {{baseUrl}}/api
Accept: text/html

GET {{baseUrl}}/

GET {{baseUrl}}/api
Content-Type: application/json

GET {{baseUrl}}/api
Accept: application/json

OPTIONS {{baseUrl}}/api
Origin: http://localhost:3000
Access-Control-Request-Method: GET
Access-Control-Request-Headers: Content-Type,Authorization

GET {{baseUrl}}/api/nonexistent

GET {{baseUrl}}/api/malformed-endpoint?invalid-param= 