@baseUrl = http://localhost:8085/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcXVhcml1bS1hcGkiLCJpYXQiOjE3NTEyMzUxNDksImV4cCI6MTc1MTMyMTU0OSwic3ViIjoiNDMiLCJ1c2VybmFtZSI6IjE3NTEyMzUxNDJAZXhhbXBsZS5jb20ifQ.2FXEtWaEfFGO2jZdI2klgceY6DTPOdxiN80cgWfd8PU

GET {{baseUrl}}/aquariums
Authorization: {{token}}

GET {{baseUrl}}/aquariums/1
Authorization: {{token}}

POST {{baseUrl}}/aquariums
Authorization: {{token}}
Content-Type: application/json

{
  "name": "My First Aquarium",
  "length": 120.0,
  "width": 60.0,
  "height": 80.0,
  "substrate": "SAND",
  "waterType": "FRESHWATER",
  "color": "Blue",
  "description": "A beautiful freshwater aquarium for tropical fish",
  "state": "SETUP"
}

POST {{baseUrl}}/aquariums
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Saltwater Paradise",
  "length": 150.0,
  "width": 80.0,
  "height": 100.0,
  "substrate": "GRAVEL",
  "waterType": "SALTWATER",
  "color": "Clear",
  "description": "Marine aquarium for coral reef setup",
  "state": "SETUP"
}

PUT {{baseUrl}}/aquariums/1
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Updated Aquarium Name",
  "length": 120.0,
  "width": 60.0,
  "height": 80.0,
  "substrate": "GRAVEL",
  "waterType": "FRESHWATER",
  "color": "Green",
  "description": "Updated description with new substrate",
  "state": "ACTIVE"
}

DELETE {{baseUrl}}/aquariums/1
Authorization: {{token}}

GET {{baseUrl}}/aquariums/1

GET {{baseUrl}}/aquariums/999
Authorization: {{token}}

POST {{baseUrl}}/aquariums
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Invalid Aquarium",
  "length": -10.0,
  "width": 60.0,
  "height": 80.0,
  "substrate": "SAND",
  "waterType": "FRESHWATER",
  "color": "Blue",
  "description": "This should fail due to negative length",
  "state": "SETUP"
} 