POST http://localhost:8085/api/auth/register
Content-Type: application/json

{
  "firstName": "Tester",
  "lastName": "bruh",
  "username": "testuser@example.com",
  "password": "testpassword123"
}

POST http://localhost:8085/api/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "testpassword123"
}

POST http://localhost:8085/api/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "wrongpassword"
}

POST http://localhost:8085/api/auth/register
Content-Type: application/json

{
  "firstName": "weak",
  "lastName": "user",
  "username": "weakuser@example.com",
  "password": "123"
}