@baseUrl = http://localhost:8085/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcXVhcml1bS1hcGkiLCJpYXQiOjE3NTEyMzUxNDksImV4cCI6MTc1MTMyMTU0OSwic3ViIjoiNDMiLCJ1c2VybmFtZSI6IjE3NTEyMzUxNDJAZXhhbXBsZS5jb20ifQ.2FXEtWaEfFGO2jZdI2klgceY6DTPOdxiN80cgWfd8PU

GET {{baseUrl}}/ornaments
Authorization: {{token}}

GET {{baseUrl}}/ornaments/1
Authorization: {{token}}

GET {{baseUrl}}/ornaments?aquariumId=1
Authorization: {{token}}

POST {{baseUrl}}/ornaments
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Medieval Castle",
  "color": "Gray",
  "material": "Resin",
  "description": "Large decorative castle with multiple towers",
  "isAirPumpCompatible": true,
  "aquariumId": 1
}

POST {{baseUrl}}/ornaments
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Artificial Brain Coral",
  "color": "Orange",
  "material": "Silicone",
  "description": "Realistic-looking brain coral replica",
  "isAirPumpCompatible": false,
  "aquariumId": 1
}

POST {{baseUrl}}/ornaments
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Malaysian Driftwood",
  "color": "Brown",
  "material": "Wood",
  "description": "Natural driftwood piece for aquascaping",
  "isAirPumpCompatible": false,
  "aquariumId": 2
}

POST {{baseUrl}}/ornaments
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Silk Amazon Sword",
  "color": "Green",
  "material": "Silk",
  "description": "Artificial plant that looks realistic",
  "isAirPumpCompatible": false,
  "aquariumId": 2
}

POST {{baseUrl}}/ornaments
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Lava Rock Formation",
  "color": "Black",
  "material": "Lava Rock",
  "description": "Natural volcanic rock for marine aquariums",
  "isAirPumpCompatible": true,
  "aquariumId": 1
}

POST {{baseUrl}}/ornaments
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Pirate Treasure Chest",
  "color": "Gold",
  "material": "Plastic",
  "description": "Opening treasure chest with bubbles",
  "isAirPumpCompatible": true,
  "aquariumId": 2
}

PUT {{baseUrl}}/ornaments/1
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Updated Medieval Castle",
  "color": "Dark Gray",
  "material": "High-Quality Resin",
  "description": "Large decorative castle with LED lighting",
  "isAirPumpCompatible": true,
  "aquariumId": 1
}

DELETE {{baseUrl}}/ornaments/1
Authorization: {{token}}

GET {{baseUrl}}/ornaments/1

GET {{baseUrl}}/ornaments/999
Authorization: {{token}}

POST {{baseUrl}}/ornaments
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Bubbling Volcano",
  "color": "Red",
  "material": "Ceramic",
  "description": "Volcano ornament with air pump compatibility",
  "isAirPumpCompatible": true,
  "aquariumId": 1
}

POST {{baseUrl}}/ornaments
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Lost Ornament",
  "color": "Blue",
  "material": "Ceramic",
  "description": "Ornament for aquarium that doesn't exist",
  "isAirPumpCompatible": false,
  "aquariumId": 999
} 